Repository AtomLinter/linter-swagger, pull requests merged in 2018-03, with the labels that each got.

#58 fix(package): update swagger-parser to version 4.0.2
  package.json
Labels: enhancement, greenkeeper

#57 Lint OpenAPI specs
  README.md
  lib/main.js
  spec/js-spec.js
Labels: enhancement

#59 Update devDependencies
  package.json
Labels: greenkeeper
